### ISSUE TITLE
Crash on loading custom map

### ISSUE THREAD

**Issue by mikemallon99** [nanaian/merlon#50]
Changed some code so kmr_20 now redirects to tst_01, and made some edits to the test_01 stage using Star Rod. I then copied the binary files from star rod over to my merlon project and tried to run, but crashed when trying to load the stage. Attached file contains all assets, the output ROM, and the .merlon distributable
[custom_map_assets.zip](https://github.com/nanaian/merlon/files/11912419/custom_map_assets.zip)

**Comment by nanaian** [comment]
This is a similar issue to the one @Wrymouth is running into. I believe @Rainchus has got this working, so it is _possible_ (just very happy to crash, it seems!).

@HailSanta (Clover) is working on a release of Star Rod that is specifically built for decomp usage. If that doesn't resolve this problem, this may be a shiftability issue and needs to be reported to pmret/papermario.

**Comment by Wrymouth** [comment]
SR uses a different build system when linked to a decomp folder than when linked to a standard mod folder. The problem is that the most recent decomp commit changed the file structure a bit so SR doesn't work with it anymore. The solution (for now) is to set up a seperate outdated decomp repo, and point SR to it
`git clone https://github.com/pmret/papermario.git && cd papermario && git checkout f0a9274c0182d11ba50a399127504360a33fc065`
